# Create a new user
POST http://localhost:8000/users/
Content-Type: application/json

{
  "aadhaarnumber": 123456789,
  "password_hash": "password123",
  "new_address": "434 street NY"
}

### Create a new agency
POST http://localhost:8000/agencies/
Content-Type: application/json

{
  "agency_id": "agency124",
  "password_hash": "agency_password"
}

###

GET  http://localhost:8000/


### Get active requests for a specific agency
GET http://localhost:8000/active-request-for-agency/agency124

### Create an active request
POST http://localhost:8000/active-requests/
Content-Type: application/json

{
  "user_aadhaarnumber": 123456783,
  "agency_id": "agency123",
  "new_address": "New Address for User 123456789"
}
