# Create a new user
POST http://localhost:8000/users/register
Content-Type: application/json

{
  "aadhaarnumber": 123456789,
  "password_hash": "password123",
  "new_address": "434 street NY"
}

### Create a new agency
POST http://localhost:8000/agency/register
Content-Type: application/json

{
  "agency_id": "agency2",
  "password_hash": "agency_password"
}

###

GET  http://localhost:8000/


### Get active requests for a specific agency
GET http://localhost:8000/requests/active-requests/agency2

### Create an active request
POST http://localhost:8000/requests/Create-requests
Content-Type: application/json

{
  "user_aadhaarnumber": 661234567873,
  "agency_id": "agency2",
  "new_address": "New Address for User 123456789"
}
